### PR TITLE
fix: set exec for nginx entrypoint

### LINKED ISSUE #1050: nginx frontend permissions issue migrating to single image
## Description of the issue
Frontend contanier does not start up migrating from multi image to single image. This is on version-13. I am including one custom app (check_run).

## Context information (for bug reports)
Here is my apps.json:
```
{
  "url": "https://github.com/frappe/erpnext",
  "branch": "version-13"
},
{
  "url": "https://github.com/agritheory/check_run",
  "branch": "version-13"
}
```

## Steps to reproduce the issue

1. create new single images according to new custom image document: https://github.com/frappe/frappe_docker/blob/main/docs/custom-apps.md
2. Modify docker-compose.yml as recommended in the migration document: https://github.com/frappe/frappe_docker/blob/main/docs/migrate-from-multi-image-setup.md
3. start up the project
4. check docker-compose logs

### Observed result
frontend container does not start up, specific error is:

```
$ docker compose -p frappe_docker -f docker-compose.yml logs frontend
frappe_docker-frontend-1  | standard_init_linux.go:230: exec user process caused: permission denied
frappe_docker-frontend-1  | standard_init_linux.go:230: exec user process caused: permission denied
```

### Expected result
frontend container should start up and serve the site

### Additional information:
```
$ docker compose -p frappe_docker -f docker-compose.yml run -it frontend /bin/bash
...
frappe@a98903ed1ba7:~/frappe-bench$ ls -l /usr/local/bin/nginx-entrypoint.sh
-rwx------ 1 root root 1502 Jan 19 20:27 /usr/local/bin/nginx-entrypoint.sh

```
```
$ cat docker-compose.yml
...
  frontend:
    depends_on:
      backend:
        condition: service_started
      websocket:
        condition: service_started
    environment:
      BACKEND: backend:8000
      CLIENT_MAX_BODY_SIZE: 50m
      FRAPPE_SITE_NAME_HEADER: $$host
      PROXY_READ_TIMOUT: "120"
      SOCKETIO: websocket:9000
      UPSTREAM_REAL_IP_ADDRESS: 127.0.0.1
      UPSTREAM_REAL_IP_HEADER: X-Forwarded-For
      UPSTREAM_REAL_IP_RECURSIVE: "off"
    image: trustedcomputer/erpnext-single-image:1.0.0
    command:
      - nginx-entrypoint.sh
    networks:
      default: null
    ports:
    - mode: ingress
      target: 8080
      published: "8080"
      protocol: tcp
    volumes:
    - type: volume
      source: sites
      target: /home/frappe/frappe-bench/sites
      volume: {}
...
```

### PR DESCRIPTION
**Pull request by revant**
for OS that mess up permission

fixes #1050

### CODE REVIEW

**Comment by revant** [comment]
@put3r-r00t3r 

Can you test a PR from my fork?

you will need to change the clone command to 

```shell
git clone https://github.com/revant/frappe_docker -b fix-1050
cd frappe_docker
```

Then continue test the build process.

**Review by sdfateh — APPROVED** [review]
I can confirm this as a solution, it works for me

**Comment by revant** [comment]
This PR is merged because I don't wish to keep explaining linux file perm.

I use linux runners to build images and they work. check this build of my custom app https://gitlab.com/castlecraft/k8s_bench/-/jobs/3624192714 it has a successful response from site created by helm release setup.

**Comment by put3r-r00t3r** [comment]
$ git clone https://github.com/revant/frappe_docker -b fix-1050
Cloning into 'frappe_docker'...
fatal: Remote branch fix-1050 not found in upstream origin

**Comment by put3r-r00t3r** [comment]
I pulled the new changes and still got similar results:

```
$ docker compose -p frappe_docker -f docker-compose.yml logs frontend
frappe_docker-frontend-1  | /bin/bash: /usr/local/bin/nginx-entrypoint.sh: Permission denied
```
```
...
$ docker compose -p frappe_docker -f docker-compose.yml run --rm -it frontend /bin/bash
frappe@6e32b05ef448:~/frappe-bench$ ls -l /usr/local/bin/nginx-entrypoint.sh
-rwx--x--x 1 root root 1502 Jan 19 20:27 /usr/local/bin/nginx-entrypoint.sh
```

**Comment by sdfateh** [comment]
@put3r-r00t3r 

try the edit here #1053 
it will solve your case, confirm if your problem solved

**Comment by put3r-r00t3r** [comment]
@sdfateh Based on the changes I observed being made, I changed images/custom/Containerfile myself to see if I could fix it. After I fixed /usr/local/bin/nginx-entrypoint.sh, I also had a problem with it reading /templates/nginx/frappe.conf.template. Finally I got it up and running with below:

```
    && chmod +x /usr/local/bin/nginx-entrypoint.sh \
    && chown frappe:frappe /usr/local/bin/nginx-entrypoint.sh \
    && chmod 644 /templates/nginx/frappe.conf.template \
    && chown frappe:frappe /templates/nginx/frappe.conf.template
```

There may be more conservative changes that will also fix the perm problems.

**Pull request merged**
