### PR TITLE
feat: kubernetes installation

### PR DESCRIPTION
**Pull request by revant**
helm chart for erpnext
job resources to create, backup, migrate sites

- [x] frappe helm chart
- [ ] auto create basic statefulset for mariadb, if mariadb host not provided.
- [ ] auto create basic statefulset for NFS provisioner, if no storageClass is specified
- [ ] package helm charts and create repository. e.g helm-charts.erpnext.org
- [ ] docs for values.yml on helm chart(s) README
- [ ] docs for k8 jobs to create, backup and migrate sites

### CODE REVIEW

**Comment by ddavidebor** [comment]
Wonderful work!

**Comment by revant** [comment]
Testing it on a cluster:

1. We need mariadb pre installed. recommended to use managed db or separate vps for mariadb
    - for testing install mariadb helm chart
    - create namespace `kubectl create namespace mariadb`
    - download and edit values.yaml https://raw.githubusercontent.com/helm/charts/master/stable/mariadb/values.yaml
    - edit values.yaml and add frappe related mysql.cnf in master and slave extraInitContainers configuration
    - install mariadb `helm install -n mariadb mariadb stable/mariadb -f /tmp/values.yaml`
2. We need RWX storage. https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes
    - If provider specific RWX is available use that
    - Install nfs helm chart if RWX is not available from provider
    - get https://raw.githubusercontent.com/helm/charts/master/stable/nfs-server-provisioner/values.yaml
    - enable `persistence` and set provider specific storageClass
    - create namespace `kubectl create namespace nfs`
    - install helm chart `helm install -n nfs nfs stable/nfs-server-provisioner -f /tmp/values.yaml`
3. Install ERPNext helm chart
    - `cd installation/kubernetes/helm-charts && helm install erpnext-edge -n erpnext erpnext`
    - `kubectl edit deployments.apps -n erpnext erpnext-edge-worker-{s,l,d}` and remove all healthcheck probes
    - `kubectl edit deployments.apps -n erpnext erpnext-edge-scheduler` and remove all healthcheck probes
4. Create resources from YAMLs as per need (for SaaS providers [kubectl client libraries](https://kubernetes.io/docs/reference/using-api/client-libraries/#officially-supported-kubernetes-client-libraries))
    - create namespace `kubectl create namespace erpnext`
    - get mariadb-root-password `export BASE64_PASSWORD=$(kubectl get secret --namespace mariadb mariadb -o jsonpath="{.data.mariadb-root-password}")`
    - resource/create-mariadb-root-password-secret.sh creates secret with for mariadb root password needed to create site
    - create secret `kubectl -n erpnext apply -f mariadbrootpasswordsecret.yaml`
    - resource/create-new-site-job.sh creates `Job` that adds new site to "bench" release
    - create job `kubectl -n erpnext apply -f newsitejob-erp.sitename.com-1583672279.yaml`
    - watch site being created `kubectl logs -n erpnext create-new-site-erp.sitename.com-57c5j --follow`
    - if job fails add FORCE=1 as `env` in newsitejob-erp.sitename.com-1583672279.yaml and retry after debugging error.
    - once Job is completed successfully and site is installed add ingress
    - resource/create-new-site-ingress.sh create ingress with site name
    - `kubectl -n erpnext apply -f newsiteingress_erp.sitename.com.yaml`

What doesn't work

- health probes don't work with 'doctor()', take too long to respond to be treated healthy
- If mariadb and nfs/storage are also on cluster the distributed nature makes is complex.
    - Saw intermittent INTERNAL SERVER ERROR (logs show not able to connect to mariadb)
    - Saw intermittent /assets/node_modules/... not found. in browser (NFS volume unavailable)

**Comment by revant** [comment]
assets-not-found

Saw the same error on latest erpnext on `develop` branch installed on native machine. Nothing related to NFS.

**Comment by revant** [comment]
healthchecks are working now

**Comment by revant** [comment]
@girip11,

You wish to take a look at this?

**Comment by girip11** [comment]
> @girip11,
> 
> You wish to take a look at this?

About reviewing this PR? I have no prior experience with Kubernetes.

**Comment by revant** [comment]
I've added README

https://github.com/revant/frappe_docker/tree/kubernetes/installation/kubernetes/README.md

**Comment by blaggacao** [comment]
For distributed storage, I guess based on my previous - somewhat extensive- research, I really could recommend openEBS: openebs.io

As an alternative to helm, it looks like `kustomize` is getting upstreamed: https://kustomize.io/ - so no tool dependency, but still maybe somewhat less scattered.

**Comment by revant** [comment]
please watch and star https://github.com/frappe/helm

**Comment by revant** [comment]
> openEBS

Sure, add to options. It is just change of storageClass. Provided it should support RWX.

> helm

Helm 3, has no server side dependency. Extract Templates and use.

> kustomize

Sure I don't mind. Just that all this is out of syllabus for many! Even Helm

**Pull request closed without merging**
