### PR TITLE
fix: install frappe/payments for v14 and develop

### PR DESCRIPTION
**Pull request by revant**
https://github.com/frappe/frappe_docker/issues/866

### CODE REVIEW

**Comment by revant** [comment]
@vrslev any suggestions? develop branch is hardcoded. No version specified in erpnext for payments.

**Comment by revant** [comment]
Tests need to conditionally install payments+erpnext, will fix it this week.

**Comment by vrslev** [comment]
Sorry, I stopped following the repo and the whole Frappe work.

**Comment by revant** [comment]
@vrslev can you help me with `get_latest_tags.py`

```
python3 ./.github/scripts/get_latest_tags.py --repo erpnext --version 14
{"frappe": "v14.0.0-beta.6", "erpnext": "v14.0.0-beta.7"}
```
expected : `{"frappe": "v14.0.0", "erpnext": "v14.0.0"}`

working as expected for 13.

**Comment by revant** [comment]
> Sorry, I stopped following the repo and the whole Frappe work.

@vrslev your contibution made the builds fast and efficient. Made it maintainable for me. Thanks!

Upstream is insane! You contributed towards some sanity. Thanks to you that we kept the tests before push. I was of opinion that we remove these tests.

Rant:
Now they're using version-less payments app that was sneaked in 2 days before release. That app is on develop branch with 0.0.1 mentioned in `__init__.py`. That goes in v14.0.0 release. Nothing mentioned anywhere, nothing in release notes or migration wiki that specifies this change. :man_shrugging:

**Pull request merged**
