### PR TITLE
Update frappe image

### PR DESCRIPTION
**Pull request by ceefour**
1. Update base image to `debian:buster-slim`, which updates Python to 3.7 as well
2. Update Node.js to 12.16.1

### CODE REVIEW

**Comment by Thunderbottom** [comment]
Hey, we plan on completely replacing the current docker image with #84, feel free to suggest any changes there instead if you feel so.

**Comment by ceefour** [comment]
@Thunderbottom can you reconsider merging this PR?   🙏

As @revant confirmed in https://github.com/frappe/frappe_docker/pull/84#issuecomment-590218034 , that PR is only for production use. So users like me still need the docker containers for development use, which the current one sufficiently providers, although needs some updating and maintenance as I proposed in this PR.

Thank you in advance. 🙏

**Comment by Thunderbottom** [comment]
I'd suggest staying away from docker for development use. It doesn't make any sense to use docker for development to be honest.

**Comment by ceefour** [comment]
@Thunderbottom Thank you for your suggestion. Despite obvious drawbacks, there are some people who want to use Docker for development. As @revant also pointed out, Microsoft also has [specific support for this use case in VS Code](https://code.visualstudio.com/docs/remote/containers). For example, Docker makes one good (but not _the only_) alternative for developing in a hybrid team with different OSes, since we can rely on the same base image.

If the concern is the burden of maintaining a variant of docker images for development purpose, I'm offering to maintain it in this or another repository under @frappe (perhaps @frappe_docker_dev?), which I definitely need for my own purpose, and also I hope will be helpful to others who have the same need. When @revant's production PR has been merged and replaced this repo entirely, I will try to mimic the structure as close as possible while maintaining developer-friendly features e.g. `bench`. I'd be happy if you can take my offer.

**Comment by Thunderbottom** [comment]
You may do so if you feel like, but we do not plan on offering a docker for development. It just creates additional maintenance overhead which we'd like to avoid at this point. If needs be, you can setup VS Code to work with the production docker that is being worked on, since the only thing you'll be missing out inside it is bench.

**Pull request closed without merging**
