### PR TITLE
fix: install py 3.7 using pyenv

### PR DESCRIPTION
**Pull request by revant**

### CODE REVIEW

**Comment by revant** [comment]
- [ ] use `debian:bullseye-slim` image,
- [ ] install python 3.9 along with python 3.7 with pyenv,
- [ ] add `pyenv global` command to make those pythons global,
- [ ] change docs to use `python3.7` instead of  `~/.pyenv/versions/3.7.12/bin/python`.

can you co-commit the changes? @vrslev

**Comment by vrslev** [comment]
I will work sometimes on this week

**Comment by vrslev** [comment]
@revant! Working on this too😆

**Comment by vrslev** [comment]
I have a bit cleaner code. Can I force-push to this branch?

**Comment by revant** [comment]
check the latest push. I'm not using debian image because it anyway installed python3 during apt-get install.

**Comment by vrslev** [comment]
My commits based on your first commit. Changes are not compatible

**Comment by vrslev** [comment]
https://github.com/revant/frappe_docker/compare/fix-bench-image...vrslev:fix-bench-image

**Comment by vrslev** [comment]
Oops, it can't compare if changes are incompatible

**Comment by vrslev** [comment]
In my version:
- debian image is used
- python versions are not hard-coded
- pyenv is usable in container after build

**Comment by revant** [comment]
> * debian image is used

it will have 3.9.2 and 3.9.9 then.

**Comment by vrslev** [comment]
> it will have 3.9.2 and 3.9.9 then.

Using system Python is bad practice. Some libraries could be missing.

> also try init frappe-bench-v12 without python2 available in the image.

Works.


So, will we use your version or mine?

**Comment by revant** [comment]
> So, will we use your version or mine?

I'll test it and commit the changes.

**Comment by vrslev** [comment]
Great!

**Comment by vrslev** [comment]
Looks good to me! Let's wait for CI to finish.

**Review by vrslev — APPROVED** [review]

**Pull request merged**
