### PR TITLE
updated link to Docker Manual with screenshots

### PR DESCRIPTION
**Pull request by siraj-samsudeen**
1. Update the link as the old link was pointing to a wrong place
2. Took 2 screenshots - one from the manual page and another one from the Docker Desktop Preferences Screen - to make it easier for people like me to locate the setting

### CODE REVIEW

**Comment by revant** [comment]
add the images to repo

**Comment by siraj-samsudeen** [comment]
> add the images to repo
> 
> edit: add the screenshots as part of repo assets. current link to image is from unknown upload on GitHub. I'll close this PR next week if no response.

Revant, I am not sure how to add the images to the repo - do you mean that I should create them as files and then check them in the commit and then link to them. Sorry if this is too basic :)

**Comment by revant** [comment]
add directory `docs/images` and add images under that directory.

then reference the images from repo in docs 

check how bench repo README displays images

https://github.com/frappe/bench/blob/develop/README.md

**Comment by siraj-samsudeen** [comment]
Thanks a lot for the instructions - please let me know whether I have done it correctly. If there are mistakes, please bear with me and point out - I looked at the linked example - it used pictures, srcset, etc. which I was not sure was needed here or not - hence, I just added an image using md syntax.

**Pull request merged**
