### PR TITLE
Refactor renaming erpnext-assets and frappe-assets to *-nginx 

### LINKED ISSUE #98: frappe-assets should be renamed
frappe-assets/erpnext-assets name is incorrect, as the container does not only serve static assets, but it also proxies request. This is very confusing. I recommend renaming "assets" to "webserver"

### PR DESCRIPTION
**Pull request by ddavidebor**
Fixes #98

### CODE REVIEW

**Comment by revant** [comment]
If we're renaming
Let's wait for any other suggestions.

**Comment by ddavidebor** [comment]
I liked your idead of -nginx, it's very clear. Everybody knows nginx is famous for two things: static assets serving and proxy

**Comment by revant** [comment]
@Thunderbottom we need to make changes to docker hub repo.

**Comment by Thunderbottom** [comment]
I think calling it `frappe-nginx` doesn't make sense, cause it's not just for the nginx service since it includes assets as well. I agree that calling it `frappe-assets` and `erpnext-assets` doesn't make sense either. I think `frappe-assets-server` and `erpnext-assets-server` sounds better? Let me know what you think, we can make changes to the dockerhub repo based on it.

**Comment by rmehta** [comment]
`frappe-static` seems like a better option

**Comment by Thunderbottom** [comment]
> `frappe-static` seems like a better option

yeah but since the assets docker also serves as a reverse proxy for serving the assets, i think specifying that it _serves_ the assets as well would make for a better name.

id say lets just take up a name and stick to it, and i'll list down what each container does in the documentation. i don't think naming anything should be such a big fuss ever.

**Comment by rmehta** [comment]
Is the `assets` docker both revere proxy or only for asset serving? Do we have another docker for nginx ?

**Comment by revant** [comment]
> Is the assets docker both revere proxy or only for asset serving? Do we have another docker for nginx ?

Yes it is both reverse proxy and serving assets

frappe-nginx

**Comment by rmehta** [comment]
ok, then `frappe-nginx` is a better name

**Comment by rmehta** [comment]
Let's also make this clear in the README. What each image does and how they are connected.

**Comment by revant** [comment]
Can you close this and send it to develop branch?

I added this https://github.com/frappe/frappe_docker/wiki/Contribution-Guidelines

**Comment by ddavidebor** [comment]
> Can you close this and send it to develop branch?
> 
> I added this https://github.com/frappe/frappe_docker/wiki/Contribution-Guidelines

I've changed the base.



> Let's also make this clear in the README. What each image does and how they are connected.

I have added a description to #94

**Comment by revant** [comment]
@chabad360 travis needs fixed https://github.com/frappe/frappe_docker/pull/93

https://travis-ci.org/frappe/frappe_docker/jobs/658478555

**Comment by chabad360** [comment]
This needs to be merged for the develop branch to build successfully. Can we stop bike-shedding please?

**Pull request merged**
