### PR TITLE
ci: do not build arm64 images

### PR DESCRIPTION
**Pull request by revant**
Only build arm64 for bench images

for #772

### CODE REVIEW

**Review by vrslev — CHANGES_REQUESTED** [review]
Remove [`platforms` input](https://github.com/frappe/frappe_docker/pull/733/files#diff-b7dce24085c1061be7542e1f68edac2c9002799454a47708546d1e7e6fbf2a10) and ["Setup QEMU" step](https://github.com/frappe/frappe_docker/pull/737/files) from reusable workflow. Everything else is fine.

**Review by vrslev — APPROVED** [review]

**Comment by carstenblt** [comment]
Would be great if you would reconsider - it was a great addition and I believe more and more people will use arm instances on AWS, as they are cheaper. I am back to building it locally.

**Comment by revant** [comment]
It won't be considered as long as python builds become faster for pandas and numpy on arm64.
It always takes 1+ hour to build arm64 images.

If you wish to use arm64, you can always build the arm64 images from same code base locally and use it through your custom container registry.

**Comment by Morakhiyasaiyam** [comment]
> Would be great if you would reconsider - it was a great addition and I believe more and more people will use arm instances on AWS, as they are cheaper. I am back to building it locally.

Hey can you guide me how to build it locally!
I tried with  " docker build . "
But throwing dome environment variables requirements but it would be nice if there is script for local build

**Comment by Morakhiyasaiyam** [comment]
Or if you already build arm64 images for yourself then can you send me link for it .now i am using official images of v14.0.2.beta

**Comment by carstenblt** [comment]
I haven't built out myself since the big update. It's interesting, that it takes so long to cross compile. I believe it took like 15 minutes on my arm MacBook.

I will build a new version soon. I can push it to a public docker repo, but I won't maintain it and trusting a stranger on the internet is always a bad idea ;)

**Comment by Morakhiyasaiyam** [comment]
> I haven't built it myself since the big update. It's interesting, that it takes so long to cross compile. I believe it took like 15 minutes on my arm MacBook.
> 
> I will build a new version soon. I can push it to a public docker repo, but I won't maintain it and trusting a stranger on the internet is always a bad idea ;)

I tried to build it on my arm64 device but its crashing device after some commands
@revant is not possible to build arm64 images for not daily but but atleast only after some major update and only for stable and latest v14 ? Once in a while?

**Comment by revant** [comment]
can you try it on custom arm64 vm?

https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners

is this works may be we can think of something.

**Pull request merged**
