### PR TITLE
Update docker-build-push.yml to support arm64

### PR DESCRIPTION
**Pull request by rexeo-asia**
> Please provide enough information so that others can review your pull request:
To include arm64 build in https://hub.docker.com/r/frappe/erpnext/tags

> Explain the **details** for making this change. What existing problem does the pull request solve?
To support arm64 container image

### CODE REVIEW

**Comment by revant** [comment]
We'll be adding this PR to the list of slow builds

Read here: https://github.com/frappe/frappe_docker/wiki/Frequently-Asked-Questions#how-to-build-arm64-images

**Comment by revant** [comment]
Show we just do the merge, fail and revert for the PR "Hall of fame"? OR close this without that?
Because the maintenance overhead is on me.

**Comment by revant** [comment]
@rexeo-asia can you try it under your github/actions? can you re-check the build times? If there is any improvement after these years, we'll merge.

**Comment by revant** [comment]
https://github.com/frappe/frappe_docker/pull/1508/commits/c04ffb8ac3fd92bb0c86aa80e7f4e50fd5e0ff9a

Seems to be building faster now. Will merge.

**Comment by revant** [comment]
#1511 

@rexeo-asia arm64 images not pushed somehow.

**Comment by rexeo-asia** [comment]
> #1511
> 
> @rexeo-asia arm64 images not pushed somehow.

just added new PR for your review. thanks brother from another mother

**Pull request merged**
