### PR TITLE
Moving to an automatic start system

### PR DESCRIPTION
**Pull request by chabad360**
Upon running `./dbench setup docker`, frappe will automaticaly be installed and started-up by an entrypoint script.

### CODE REVIEW

**Comment by gavindsouza** [comment]
@chabad360 what's the status on this?

**Comment by chabad360** [comment]
it works.frappe/frappe_docker wrote:@chabad360 what's the status on this?

**Comment by ceefour** [comment]
Is this together with or conflicts with #84  ?

**Comment by chabad360** [comment]
This completely conflicts (unfortunately, it was a lot of effort), but for
the time being I'm leaving it open.

**Comment by revant** [comment]
We'll have dev containers later again.

Do get back if you explore vscode devcontainers.

I wish:

- clone this repo
- open in vscode
- click dev-container icon
- start development + watch/rebuild + debugging

**Pull request closed without merging**
