### PR TITLE
 fix: Letterheads missing

### LINKED ISSUE #703: Letterheads missing
Add a Letter Head with HTML called `Example` :

```html
<div style="text-align: center;">
  <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Erpnext_logo.svg/240px-Erpnext_logo.svg.png" width="10%">
  <div style="font-size: 30px;">Example Limited</div>
</div>
```

Create a new Note: "Hello Letterhead from containers"

Set letterhead: `Example`

print pdf

Does it have anything to do with the wkhtmltopdf binary? Initially it was not pulled from distro repos, It was downloaded from project's github assets/releases.

https://github.com/frappe/frappe_docker/blob/95aeb32e2d1d3d5754bf4f97d8af650d462488d1/build/frappe-worker/Dockerfile#L63-L68

FAQ entry about different downloads https://wkhtmltopdf.org/downloads.html#why-do-you-have-static-builds-with-patched-qt

_Originally posted by @revant in https://github.com/frappe/frappe_docker/issues/661#issuecomment-1068903059_

### PR DESCRIPTION
**Pull request by vrslev**
Closes #703

### CODE REVIEW

**Comment by vrslev** [comment]
CI won't run. @revant Can you test locally? It works for me, by the way.

**Comment by vrslev** [comment]
Waiting for ci: https://github.com/frappe/frappe_docker/actions/runs/1993567510

**Comment by vrslev** [comment]
Reran here: https://github.com/vrslev/frappe_docker/runs/5572306967?check_suite_focus=true, passes. @revant waiting for your review.

**Comment by revant** [comment]
I built the images and I'm getting following error when I print PDF

```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 66, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 31, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 68, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1233, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/print_format.py", line 93, in download_pdf
    frappe.local.response.filecontent = get_pdf(html)
  File "apps/frappe/frappe/utils/pdf.py", line 37, in get_pdf
    filedata = pdfkit.from_string(html, False, options=options or {})
  File "env/lib/python3.9/site-packages/pdfkit/api.py", line 72, in from_string
    return r.to_pdf(output_path)
  File "env/lib/python3.9/site-packages/pdfkit/pdfkit.py", line 156, in to_pdf
    raise IOError('wkhtmltopdf reported an error:\n' + stderr)
OSError: wkhtmltopdf reported an error:
Exit with code 1 due to network error: HostNotFoundError
```

I'll rebuild with no cache and check again.

**Review by revant — COMMENTED** [review]
can anyone test it by generating actual pdf from a note?

although the setup now uses patched wkhtmltopdf, merging this will be more regression than just missing letterhead.

**Comment by vrslev** [comment]
@revant It works on version 13, but not on develop branch. I think issue is in Frappe code, not our setup.
Screenshot 2022-03-18 at 10 43 17

**Comment by vrslev** [comment]
Merging?

**Pull request merged**
