### PR TITLE
refactor: Dockerfiles

### PR DESCRIPTION
**Pull request by vrslev**
This PR aims to:
- unify different software installation among all Dockerfiles (e.g. Node),
- update software,
- begin following some Dockerfile best practices,
- reduce images sizes (for zero cost).

In all images:
- Update Node and nvm,
- Remove nvm cache (10–20 MB),
- Add wkhtmltopdf version variable,
- Unify Node and wkhtmltopdf installation,
- Remove `apt-get clean` (https://github.com/rocker-org/rocker/issues/35#issuecomment-58944297),
- Add `--no-install-recommends` flag in `apt-get install` commands,
- Separate apt and others installs for faster downloads (smaller layers),
- Use pip instead of pip3 alias,
- Use `FROM ... as builder` and `COPY --from=builder ...`,
- Style.

## frappe-worker
- Install gcc and g++ only on arm64 (tested on Apple M1),
- Install wheel (to avoid legacy `setup.py` usage),
- Change order of steps for better caching on local builds.

## frappe-nginx
- Remove unnecessary node, npm and yarn presence check

## frappe-socketio
- Remove unnecessary node, npm and yarn presence check

## erpnext-nginx
- Refactor install_app script,
- Don't install unused wget,
- Install ca-certificates (they get expired from time to time).

## bench
- Reduced unpacked image size up to 0.5 GB:
```
frappe/bench             latest     9bc43da1d05b   25 minutes ago   959MB
frappe/bench             <none>     57f87b9b9170   15 hours ago     1.49GB
```
- Don't install wkhtmltopdf from apt (already installing version from GitHub Releases),
- Merge relevant one-line steps,
- Replace legacy `libmariadbclient-dev` with `libmariadb-dev`,
- Added `DEBIAN_FRONTEND=noninteractive`: there's request to readline frontend in some package installation.

Also changed test workflow to allow to trigger tests manually.

### CODE REVIEW

**Comment by vrslev** [comment]
@revant Should we stop installing Node v10 in bench image?

**Comment by revant** [comment]
> @revant Should we stop installing Node v10 in bench image?

it was there for v11 development I guess

**Comment by vrslev** [comment]
> it was there for v11 development

It is quite old 😃 Removing?

**Comment by vrslev** [comment]
Also, is rebuilding Frappe assets required in erpnext-nginx?

**Comment by revant** [comment]
> Removing?

let's keep it. Somewhere I read last 3 versions are officially supported. let's remove it on release of v14?

> Frappe assets required in erpnext-nginx?

try it without building frappe assets? does the ui, wizard work?

**Comment by vrslev** [comment]
>  let's remove it on release of v14?

Sure.

> try it without building frappe assets? does the ui, wizard work?

Nope. We have to install rollup and other dependencies to build assets. Made some changes anyway: https://github.com/frappe/frappe_docker/pull/550/commits/53e68f0f70bc7e7a77a4f7d79802dd1749ea9437

**Comment by vrslev** [comment]
Not done yet.

**Pull request closed without merging**
