### PR TITLE
feat: remove version-12 dependencies

### PR DESCRIPTION
**Pull request by FHenry**
As https://discuss.erpnext.com/t/upgrade-to-version-13-or-newer-to-continue-receiving-regular-fixes/93052
version-12 is no more supported, we can remove it from docker bench image

closes : #896

### CODE REVIEW

**Comment by revant** [comment]
should we remove it from bench image?
people may be using it to develop their v12 custom apps?

**Comment by FHenry** [comment]
Hi @revant 
Yes I wonder also...
I made this PR because I see the announcement on the forum, and as I play with bench imagea lot, I think it can be good to have only "supported" inside.

May be should I update the PR with another dockerfile  and add some documentation for older version ?

What do you think ?

**Comment by revant** [comment]
> May be should I update the PR with another dockerfile and add some documentation for older version ?

Should we just tag and push existing bench as `version-12` tag, then deprecate code and continue with daily `latest` builds. People who want to develop version-12 will stick to `version-12` tag.

**Comment by FHenry** [comment]
Sounds very good.
Tag version-12 is actual one and merge this PR for lastest ?
Only you car create tag can do that (and I'm happy with that ;-))

**Comment by revant** [comment]
Tag is good, We may also need branches like `version-10`. I'll create those. Docker hub has some policy where they remove image tags that are not used (not sure about latest updates). So if we tag there is a chance of the image tag to be deleted. In that case branch will help users build their own images.

**Comment by revant** [comment]
I've created `version-12` branch. Manually building and pushing `frappe/bench:version-12`

**Comment by FHenry** [comment]
Nice, so we can go for `main` branch only version-13 and version-14 by merging this pr ?

**Comment by revant** [comment]
image: frappe/bench:version-12 is available now.

**Pull request merged**
