### PR TITLE
Tool to replace dbench

### PR DESCRIPTION
**Pull request by chabad360**
This PR adds the `bench` script, which aims for near parity with frappe bench, it makes setting up far easier, because instead of running `./dbench -c "new-site site1.local"` you only white what you would if bench was installed on the local system (i.e. `./bench new-site site1.local`), it also adds other features as well.

### CODE REVIEW

**Comment by Thunderbottom** [comment]
rename the file to something that is not `bench`? `bench-docker` would be good I guess.

**Comment by chabad360** [comment]
Just curious, Why?

**Comment by Thunderbottom** [comment]
Just so to not confuse people with the actual bench command. Also, is this really necessary? Why not just append the changes to `dbench`

**Comment by chabad360** [comment]
No issue doing that, I just didn't want to get "influenced" by the existing code, so I stared again, but I will do this.

**Comment by chabad360** [comment]
Ready for merge

**Pull request merged**
