### PR TITLE
fix: make changes for backward compat

### PR DESCRIPTION
**Pull request by revant**
make changes for refactor to work on existing setups

### CODE REVIEW

**Comment by vrslev** [comment]
Why?

**Comment by vrslev** [comment]
If we're merging that one, this one will be gone. Maybe create another branch?

**Comment by revant** [comment]
I'll create another branch.

Just for reference. If anyone doesn't want to setup the new compose then they can just pull this "branch" and keep working with existing setup.

What should the branch be called?

**Comment by revant** [comment]
https://github.com/frappe/frappe_docker/tree/compat

**Pull request closed without merging**
