### PR TITLE
feat(frappe-nginx): use nginxinc/nginx-unprivileged image

### PR DESCRIPTION
**Pull request by revant**
#567

### CODE REVIEW

**Review by Thunderbottom — APPROVED** [review]
LGTM! builds fine.

**Comment by Tus1688** [comment]
After upgrading to the latest version of frappe docker. Docker Daemon that hardened with selinux still causing issue with nginx image. Any clue?

**Comment by Thunderbottom** [comment]
Could you try adding SELinux rules for the folder that you're trying to mount within the container?

**Comment by Tus1688** [comment]
Hi @Thunderbottom, I am not sure about it. All I do is changing `/etc/docker/daemon.json`  by adding `selinux-enabled: true`

**Comment by Thunderbottom** [comment]
Well, right now I don't really have a system that runs selinux, and neither do I have the capacity for the mental gymnastics that one requires to set it up correctly. Maybe for now you can try replacing `:rw` with the `:z` option in your docker-compose's volume mountpoint and report back:

```yaml
volumes:
  - sites-vol:/var/www/html/sites:z
  - assets-vol:/assets:z
```

The `:z` option should basically ask selinux to relabel the filesystem correctly so that it can be mounted inside the container. Let me know how it goes for you.

**Comment by Tus1688** [comment]
I have tried them and unfortunately it's not working, I also did `restorecon -R -v /var/lib/docker` and `restorecon -R -v /usr/bin`

**Pull request merged**
