### PR TITLE
update to VS Code version 1.64.2

### PR DESCRIPTION
**Pull request by restlessronin**
I modified the VS Code Devcontainer related files to fix warnings issued by VS Code 1.64.2 (current as of Mar 1, 2022).

There are 3 changes.
1. Changed `addPorts` to `forwardPorts`
2. Changed setup of linux shell
3. Changed VS Code browser preview extension.

### CODE REVIEW

**Comment by vrslev** [comment]
@restlessronin There’s #617 coming. Please wait for it and send a PR again 🙏

**Comment by revant** [comment]
it's still `appPort`, should it be `forwardPorts`?

**Comment by restlessronin** [comment]
> We merged refactor branch. I added commits, hope you don't mind. `settings.json` is added to gitignore, so I added settings to devcontainer. Are you happy with the changes?

Seems to open fine in the devcontainer. I'm not an expert on VS Code settings, so I don't really have an opinion on where those setting should go. I was just trying to get rid of the warnings that VS Code was generating on the old files.

Basically it's fine as far as I'm concerned.

**Comment by vrslev** [comment]
> it's still appPort, should it be forwardPorts?

@revant Nope, it is forwardPorts

**Comment by restlessronin** [comment]
> it's still `appPort`, should it be `forwardPorts`?

It's `forwardPorts` in the file that I'm looking at.

**Pull request merged**
