### PR TITLE
ci: fix inputs.platforms

### LINKED ISSUE #781: CI fails
CI fails after #777: https://github.com/frappe/frappe_docker/actions/runs/2158948806

### PR DESCRIPTION
**Pull request by revant**
fixes #781

### CODE REVIEW

**Comment by revant** [comment]
@vrslev this should work?

**Comment by vrslev** [comment]
We don't use this input. I'd remove it instead.

**Comment by revant** [comment]
removed input.platforms

**Review by vrslev — APPROVED** [review]

**Comment by revant** [comment]
build_develop is failing. One retry for good luck? Or any scientific finding? :sweat_smile: 
https://github.com/frappe/frappe_docker/runs/6002408124?check_suite_focus=true

**Comment by vrslev** [comment]
Retry worked :)

**Pull request merged**
