### PR TITLE
fix: change unpriviliged nginx port from 80 to 8080

### PR DESCRIPTION
**Pull request by revant**
fixes https://github.com/frappe/frappe_docker/issues/574#issuecomment-974774363

```
2021/11/21 08:10:38 [emerg] 1#1: bind() to 0.0.0.0:80 failed (13: Permission denied)
```

### CODE REVIEW

**Comment by revant** [comment]
assets-vol, sites-vol, logs-vol need to be 1000:1000 uid:gid permission before starting nginx. Any ideas?

**Comment by vrslev** [comment]
Do we need to use `nginxinc/docker-nginx-unprivileged` image?

**Comment by revant** [comment]
> Do we need to use `nginxinc/docker-nginx-unprivileged` image?

mostly yes.
it is ready made image that allows non root user to run nginx.
it does need some tweaks to configs.

https://github.com/nginxinc/docker-nginx-unprivileged/blob/02a4307966e5b5d07226cb7251afa821adb0e297/Dockerfile-debian.template#L100

**Comment by vrslev** [comment]
> it is official image by nginx inc.

ok, didn’t know that :)

**Pull request merged**
