### PR TITLE
frontend depends_on websocket to avoid error on startup

### PR DESCRIPTION
**Pull request by tengkuizdihar**
> Please provide enough information so that others can review your pull request:

I tend to run open source project locally, preferably by running the docker compose. I ran it using `docker-compose -f ./pwd.yml up -d`.

> Explain the **details** for making this change. What existing problem does the pull request solve?

After running docker compose, the `frontend` container is dead. Doing `docker logs frappe_docker_frontend_1` reveals the log below:

```
2024/01/23 10:46:13 [emerg] 3#3: host not found in upstream "websocket:9000" in /etc/nginx/conf.d/frappe.conf:6
```

This mean the websocket service has not yet started when running frontend. To fix this, I use `depends_on` attribute for the frontend service. https://docs.docker.com/compose/compose-file/compose-file-v3/#depends_on.

### CODE REVIEW

**Comment by tengkuizdihar** [comment]
please review this, thank you @revant

**Review by sdfateh — APPROVED** [review]

**Comment by revant** [comment]
use pre-commit before sending PR.

This PR will automatically closed if there is no response.

**Comment by revant** [comment]
If there is any error with pre-commit that you cannot fix then share here.

**Comment by tengkuizdihar** [comment]
was just about to install pre-commit and yarn, thanks

**Pull request merged**
