### PR TITLE
Update version from edge to v13 in Docker production environment

### PR DESCRIPTION
**Pull request by vasanthv16**
In Docker production environment, the version number environment properties should refer to v13 so that the latest production images get pulled instead of edge (which, I believe, is created from the develop branch).

### CODE REVIEW

**Comment by revant** [comment]
In real production scenario you don't need just v13. You need v13.0.2 and v13.0.1 and that needs to change for every release.

I'll wait for someone to comment. Docs mention to change version in production.

**Comment by vasanthv16** [comment]
In the docker images, v13.0.2 (or the latest 13.x.x) is also tagged as 13. So just pointing to v13 gives the latest version. I did an install yesterday with v13 for erpnext and frappe, adn the versions installed were:

ERPNext: v13.0.1 (version-13)
Frappe Framework: v13.0.2 (version-13)

So we only need to update this once every major release.

Also, can you please point me to the doc where it asks to change the version?

**Comment by revant** [comment]
@Thunderbottom any comments?

As per me:

- Tests will need changes https://github.com/frappe/frappe_docker/blob/12d9760658a0f7c05b53c34682b21d37ccfd9339/tests/docker-test.sh#L52 these changes are not considered in the PR.
- Why pull request on master branch? Contribution doc mentions correct branches https://github.com/frappe/frappe_docker/blob/develop/CONTRIBUTING.md#branches (don't resend to develop branch)

> Also, can you please point me to the doc where it asks to change the version?

https://github.com/frappe/frappe_docker/blob/develop/docs/single-bench.md#setup-environment-variables

https://github.com/frappe/frappe_docker/blob/develop/docs/multi-bench.md#setup-environment-variables

https://github.com/frappe/frappe_docker/blob/develop/docs/docker-swarm.md#deploy-frappeerpnext (check enviornment variables)

**Comment by vasanthv16** [comment]
Thanks for the references to doc on changing the version. I was looking at https://github.com/frappe/bench#docker-installation-for-production mainly. It just felt like env-production should point to production images and not development images.

As for the tests, I can update it too. But conceptually, if you don't want to accept this pull request, that is fine.

>> Why pull request on master branch?
Yeah, I see the instructions now. Missed that earlier. My bad.

**Comment by revant** [comment]
I think frappe/bench should directly link to frappe_docker.

Generally docker users contribute updates to docs on frappe_docker keeping it up to date.

**Comment by revant** [comment]
@vasanthv16 send a PR to frappe/bench to update the README?

**Comment by vasanthv16** [comment]
Sure. I agree with your point about bench redirecting to frappe_docker. As someone new(ish) to ERPNext (last I looked at it was a few years back), I could see some potential for improvement to the installation doc. I will send a PR for it.

**Pull request closed without merging**
