### PR TITLE
Add a build script for travis.yml

### PR DESCRIPTION
**Pull request by chabad360**
This PR adds a script that shrinks `travis.yml` by putting the common actions into a script (appropriately called `travis.sh`), which should help simplify writing an addition to `travis.yml`.

### CODE REVIEW

**Comment by Thunderbottom** [comment]
we should actually do a shell script instead of a python script

**Comment by chabad360** [comment]
I did that, but it's much more bloated...

**Comment by revant** [comment]
can you close this and send it to develop branch?

I just made https://github.com/frappe/frappe_docker/wiki/Contribution-Guidelines

**Comment by chabad360** [comment]
> can you close this and send it to develop branch?

Done by @Thunderbottom  .

**Comment by revant** [comment]
@chabad360 Builds failed, can you check

https://travis-ci.org/frappe/frappe_docker/jobs/658475136

**Comment by chabad360** [comment]
@revant the script needs py3

**Comment by chabad360** [comment]
> fixed using bionic for travis.

That's because bionic defaults to python3, but that doesn't actually help as this PR was written with #100 in mind, so while the images might build, everything is broken in the compose files.

**Pull request merged**
