### PR TITLE
chore: Use pre-commit framework

### LINKED ISSUE #602: Use Pre-commit for code quality
[Pre-commit](https://pre-commit.com) is `A framework for managing and maintaining multi-language pre-commit hooks.` We could use it to improve code quality. Frappe started using it in multiple repos why don't we? I use it in all my projects and it really helps to keep style consistent. I can provide pre-commit config. 

@revant Thoughts?

### PR DESCRIPTION
**Pull request by vrslev**
- Added .editorconfig
- Added pre-commit config
- Updated lint workflow to use pre-commit
- Added pre-commit autoupdate workflow to update hooks once a week
- Added guide to CONTRIBUTING.md

Closes #602

### CODE REVIEW

**Comment by vrslev** [comment]
It is supposed to fail.

@revant Look what happens after running `pre-commit` on all files: https://github.com/vrslev/frappe_docker/compare/pre-commit...pre-commit-output

**Comment by revant** [comment]
Is there a way for users to format/lint things locally before sending the PR?

Add those commands to CONTRIBUTING.md

**Comment by vrslev** [comment]
@revamt Sure it is. See https://github.com/frappe/frappe_docker/blob/31b1e9c4d7e59580d434b66fc0be6dd545ddc0af/CONTRIBUTING.md

**Comment by vrslev** [comment]
Are you comfortable with reformatting half of codebase (~30 files) in a single PR?

**Comment by revant** [comment]
If you wish we can add the hook last and change types of files in multiple commits/merges. Example, `refactor: lint Dockerfiles`,  `refactor: lint scripts`, `refactor: lint markdown`, etc.

Or just merge it! There was a huge merge here https://github.com/frappe/frappe_docker/pull/84

**Comment by vrslev** [comment]
> If you wish we can add the hook last and change types of files in multiple commits/merges. 

That’s a good idea! Let’s do this.

But first please review carefully this PR.

**Comment by vrslev** [comment]
@revant Yep.

**Review by revant — APPROVED** [review]

**Pull request merged**
