### PR TITLE
Fix lint issues

### PR DESCRIPTION
**Pull request by vrslev**
This fixes possible issues that came up while using vanilla shellcheck (with -x option only)

### CODE REVIEW

**Comment by vrslev** [comment]
@revant There's one issue left. Do we have to use `ls` and not `find`?
https://github.com/frappe/frappe_docker/blob/d1ed880c7825da06d07522b849ee03bd5bbd29e3/build/frappe-nginx/docker-entrypoint.sh#L11

**Comment by vrslev** [comment]
Don't merge. Breaks ping test after build.

**Comment by vrslev** [comment]
All good now.

**Comment by revant** [comment]
> @revant There's one issue left. Do we have to use `ls` and not `find`?

this `touch` command came as a PR, it can be improved.

**Comment by vrslev** [comment]
What would be equivalent for find?

**Comment by revant** [comment]
> What would be equivalent for find?

how about this?

```
find /assets -maxdepth 1 -name "*.*" | head -n 1
```

**Comment by vrslev** [comment]
Seems to work fine. I think we can merge after CI passes

**Comment by vrslev** [comment]
This PR also fixes integration test: https://github.com/frappe/frappe_docker/runs/4147020329?check_suite_focus=true

**Pull request merged**
